# Generated by Django 3.0.8 on 2020-07-23 19:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_auto_20200723_2019'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='brand',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='brand',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='brand',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='brand',
            name='updated_by',
        ),
        migrations.RemoveField(
            model_name='category',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='category',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='category',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='category',
            name='updated_by',
        ),
        migrations.RemoveField(
            model_name='subcategory',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='subcategory',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='subcategory',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='subcategory',
            name='updated_by',
        ),
    ]
