# Generated by Django 3.0.8 on 2020-07-27 02:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_product_is_active'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='is_active',
            new_name='active',
        ),
    ]
