# Generated by Django 3.0.8 on 2020-07-27 08:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('products', '0011_auto_20200727_0401'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
    ]
