# Generated by Django 3.0.8 on 2020-08-13 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0012_auto_20200727_1032'),
    ]

    operations = [
        migrations.AddField(
            model_name='brand',
            name='name_ar',
            field=models.CharField(blank=True, max_length=150, verbose_name='Brand_AR'),
        ),
    ]
