# Generated by Django 3.0.8 on 2020-08-13 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0013_brand_name_ar'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='name_ar',
            field=models.CharField(blank=True, max_length=150, verbose_name='Category_AR'),
        ),
    ]
