# Generated by Django 3.0.8 on 2020-08-20 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0021_auto_20200819_0058'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='balance',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='product',
            name='number_of_reviews',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='product',
            name='purchased',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='product',
            name='rating_average',
            field=models.DecimalField(blank=True, decimal_places=2, default=5.0, max_digits=3, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='reduction',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14),
        ),
        migrations.AddField(
            model_name='product',
            name='sold',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
