# Generated by Django 3.0.8 on 2020-08-20 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0022_auto_20200820_1350'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='balance',
            field=models.IntegerField(default=0),
        ),
    ]
