# Generated by Django 3.0.8 on 2020-08-23 12:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0025_slider'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='slider',
        ),
    ]
