# Generated by Django 3.0.8 on 2020-08-30 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0028_slider_lang'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='delivery_days',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
    ]
