# Generated by Django 3.0.8 on 2020-08-20 14:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('currencies', '0005_auto_20200819_0058'),
    ]

    operations = [
        migrations.RenameField(
            model_name='exchangerate',
            old_name='date',
            new_name='apply_date',
        ),
    ]
