# Generated by Django 3.0.8 on 2020-07-27 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_auto_20200727_1049'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='net_price',
            field=models.DecimalField(decimal_places=2, default=10, max_digits=14),
            preserve_default=False,
        ),
    ]
