# Generated by Django 3.0.8 on 2020-08-02 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_auto_20200727_2137'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='due_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=17),
        ),
        migrations.AddField(
            model_name='order',
            name='number_of_items',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='orderitems',
            name='product_value',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=17),
        ),
    ]
