# Generated by Django 3.0.8 on 2020-08-20 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_auto_20200802_0414'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='product_value',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14),
        ),
    ]
