# Generated by Django 3.0.8 on 2020-08-20 13:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('currencies', '0005_auto_20200819_0058'),
        ('orders', '0008_auto_20200820_1529'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='currency',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='currencies.Currency'),
        ),
        migrations.AddField(
            model_name='order',
            name='exchanged_due_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=17),
        ),
        migrations.AlterField(
            model_name='order',
            name='exchange_rate',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=17),
        ),
    ]
