# Generated by Django 3.0.8 on 2020-08-20 13:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('currencies', '0005_auto_20200819_0058'),
        ('orders', '0009_auto_20200820_1541'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='currency',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='currencies.Currency'),
        ),
    ]
