# Generated by Django 3.0.8 on 2020-08-31 00:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0015_order_shipping_fees'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='due_amount',
            new_name='total',
        ),
    ]
